version: "3.1"

services:
  dbbackups:
    image: kartoza/pg-backup
    volumes:
      - ./backups:/backups
    environment:
      - DUMPPREFIX=PG_gis
      - POSTGRES_HOST=188.166.162.242
      - POSTGRES_USER=admin
      - POSTGRES_PASS=admin123
      - POSTGRES_PORT=5432
      - CRON_SCHEDULE="*/1 * * * *"
    restart: on-failure
